steps:
  # Ngambil data env yg disimpen di cloud storage pake gsuri
  - name: "gcr.io/cloud-builders/gsutil"
    args: ["cp", "gs://kelompok-tcc-e07/tugas_tcc_faiz/.env", ".env"]

  # membuat image dengan menjalankan perintah "cloud build -t .." 
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/t7-tcc-be", "."]

  # push image yang sudah dibuat ke Artifact Registry dengan menjalankan "docker push .."
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/t7-tcc-be"]

  # Melakukan deploy ke cloud run menggunakan image yg telah di-upload/push pada langkah sebelumnya
  # Pada bagian ini, dijalankan perintah sebagai berikut.
  # "gcloud run deploy t6-tcc-be \
  #       --image 'gcr.io/$PROJECT_ID/tcc-be \
  #       --timeout 1000s \
  #       --port 3001 \
  #       --region us-central1 \
  #       --allow-unauthenticated' \ 

  # Keterangan:
  # "gcloud run deploy be": Perintah yang digunakan untuk mendeploy service ke cloud run dengan nama "be"
  # "--image 'gcr.io/$PROJECT_ID/tcc-be'": Image yang akan di-deploy
  # "--timeout 1000s": Mengatur waktu maksimum loading menjadi 1000s
  # "--port 5000": Mengatur port yang akan digunakan (disamakan dengan port yg di-listen oleh server)
  # "--region us-central1": Memilih us-central1 sebagai region yg akan digunakan pada cloud run
  # "--allow-unauthenticated": Agar BE dapat diakses di mana saja tanpa memerlukan autentikasi

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "t7-tcc-be",
        "--image",
        "gcr.io/$PROJECT_ID/t6-tcc-be",
        "--timeout",
        "3600",
        "--port",
        "5000",
        "--region",
        "us-central1",
        "--allow-unauthenticated",
      ]

# Log hanya akan disimpan di Google Cloud Logging
# Log tidak akan disimpan di Google Cloud Storage (butuh hak akses).
options:
  logging: CLOUD_LOGGING_ONLY
